import { useState } from 'react';
import { Card, Button, Input, Select, Modal } from '../../components/ui';
import { MarketingList } from '../../components/features/marketing/MarketingList';
import { Plus, Ticket, Copy, Target, TrendingUp, Users, Check } from 'lucide-react';
import { useAuth } from '../../context/AuthContext';
import type { CouponCode } from '../../types';

const mockCoupons: CouponCode[] = [
  {
    id: '1',
    code: 'FISH25',
    name: 'Fish Special Discount',
    description: '25% off on all fish items',
    discountType: 'percentage',
    discountValue: 25,
    minOrderValue: 500,
    maxDiscountAmount: 200,
    usageLimit: 1000,
    usedCount: 245,
    validFrom: '2024-01-10T00:00:00',
    validTo: '2024-01-31T23:59:59',
    isActive: true,
    targetAudience: 'all',
    applicableProducts: ['fish'],
    excludedProducts: [],
    stackable: false,
    autoGenerated: false,
    createdBy: 'Admin',
    createdAt: '2024-01-09'
  },
];

interface CouponStatsProps {
  coupons: CouponCode[];
}

function CouponStats({ coupons }: CouponStatsProps) {
  const totalUsage = coupons.reduce((sum, coupon) => sum + coupon.usedCount, 0);
  return (
    <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-6">
      <Card className="p-4"><div className="flex items-center gap-3"><div className="p-2 bg-purple-100 rounded-lg"><Ticket className="h-5 w-5 text-purple-600" /></div><div><p className="text-sm text-gray-600">Total Coupons</p><p className="text-xl font-bold">{coupons.length}</p></div></div></Card>
      <Card className="p-4"><div className="flex items-center gap-3"><div className="p-2 bg-green-100 rounded-lg"><Target className="h-5 w-5 text-green-600" /></div><div><p className="text-sm text-gray-600">Active</p><p className="text-xl font-bold">{coupons.filter(c => c.isActive).length}</p></div></div></Card>
      <Card className="p-4"><div className="flex items-center gap-3"><div className="p-2 bg-blue-100 rounded-lg"><Users className="h-5 w-5 text-blue-600" /></div><div><p className="text-sm text-gray-600">Total Usage</p><p className="text-xl font-bold">{totalUsage.toLocaleString()}</p></div></div></Card>
      <Card className="p-4"><div className="flex items-center gap-3"><div className="p-2 bg-orange-100 rounded-lg"><TrendingUp className="h-5 w-5 text-orange-600" /></div><div><p className="text-sm text-gray-600">Usage Rate</p><p className="text-xl font-bold">24.5%</p></div></div></Card>
    </div>
  );
}

interface CouponFormProps {
  initialData?: CouponCode;
  isReadOnly: boolean;
  onSubmit: (data: any) => void;
  onCancel: () => void;
}

function CouponForm({ initialData, isReadOnly, onSubmit, onCancel }: CouponFormProps) {
  const [data] = useState(initialData);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    onSubmit(data);
  };

  return (
    <form onSubmit={handleSubmit} className="space-y-4">
      <Input label="Coupon Name" defaultValue={data?.name} disabled={isReadOnly} required />
      <Input label="Coupon Code" defaultValue={data?.code} disabled={isReadOnly} required />
      <textarea className="w-full rounded-lg border p-2" rows={2} defaultValue={data?.description} disabled={isReadOnly} placeholder="Description..." />
      <div className="grid grid-cols-2 gap-4">
        <Select label="Discount Type" defaultValue={data?.discountType} disabled={isReadOnly} options={[{ value: 'percentage', label: 'Percentage' }, { value: 'fixed_amount', label: 'Fixed Amount' }]} />
        <Input label="Discount Value" type="number" defaultValue={data?.discountValue} disabled={isReadOnly} />
      </div>
      <div className="grid grid-cols-2 gap-4">
        <Input label="Min Order Value (₹)" type="number" defaultValue={data?.minOrderValue} disabled={isReadOnly} />
        <Input label="Usage Limit" type="number" defaultValue={data?.usageLimit} disabled={isReadOnly} />
      </div>
      <div className="grid grid-cols-2 gap-4">
        <Input label="Valid From" type="datetime-local" defaultValue={data?.validFrom.slice(0,16)} disabled={isReadOnly} />
        <Input label="Valid To" type="datetime-local" defaultValue={data?.validTo.slice(0,16)} disabled={isReadOnly} />
      </div>
      <div className="border-t pt-4 flex justify-end gap-2">
        <Button type="button" variant="secondary" onClick={onCancel}>Close</Button>
        {!isReadOnly && <Button type="submit">Save Changes</Button>}
      </div>
    </form>
  );
}

export function CouponPage() {
  const { user } = useAuth();
  const [coupons, setCoupons] = useState<CouponCode[]>(mockCoupons);
  const [isFormOpen, setIsFormOpen] = useState(false);
  const [isReadOnly, setIsReadOnly] = useState(false);
  const [selectedCoupon, setSelectedCoupon] = useState<CouponCode | undefined>();
  const [copiedCode, setCopiedCode] = useState('');

  const handleOpenForm = (coupon?: CouponCode, readOnly = false) => {
    setSelectedCoupon(coupon);
    setIsReadOnly(readOnly);
    setIsFormOpen(true);
  };

  const handleCloseForm = () => {
    setIsFormOpen(false);
    setSelectedCoupon(undefined);
  };

  const handleSave = (data: CouponCode) => {
    if (selectedCoupon) {
      setCoupons(coupons.map(c => c.id === data.id ? data : c));
    } else {
      setCoupons([...coupons, { ...data, id: Date.now().toString(), createdBy: user?.name || 'Admin', createdAt: new Date().toISOString() }]);
    }
    handleCloseForm();
  };

  const handleDelete = (coupon: CouponCode) => {
    if (window.confirm('Are you sure?')) {
      setCoupons(coupons.filter(c => c.id !== coupon.id));
    }
  };

  // Bulk actions handler for coupons
  const handleBulkAction = async (actionId: string, selectedIds: string[], data?: any) => {
    try {
      switch (actionId) {
        case 'activate':
          console.log(`Activating ${selectedIds.length} coupons:`, selectedIds);
          setCoupons(prev => prev.map(coupon => 
            selectedIds.includes(coupon.id) ? { ...coupon, isActive: true } : coupon
          ));
          alert(`${selectedIds.length} coupons have been activated successfully!`);
          break;
        case 'deactivate':
          console.log(`Deactivating ${selectedIds.length} coupons:`, selectedIds);
          setCoupons(prev => prev.map(coupon => 
            selectedIds.includes(coupon.id) ? { ...coupon, isActive: false } : coupon
          ));
          alert(`${selectedIds.length} coupons have been deactivated successfully!`);
          break;
        case 'delete':
          if (confirm(`Are you sure you want to delete ${selectedIds.length} coupons? This action cannot be undone.`)) {
            console.log(`Deleting ${selectedIds.length} coupons:`, selectedIds);
            setCoupons(prev => prev.filter(coupon => !selectedIds.includes(coupon.id)));
            alert(`${selectedIds.length} coupons have been deleted successfully!`);
          }
          break;
        default:
          console.log(`Bulk action ${actionId} performed on ${selectedIds.length} coupons`, data);
      }
    } catch (error) {
      console.error('Coupon bulk action failed:', error);
      alert('Bulk action failed. Please try again.');
    }
  };
  
  const handleCopy = (code: string) => {
    navigator.clipboard.writeText(code);
    setCopiedCode(code);
    setTimeout(() => setCopiedCode(''), 2000);
  };

  const renderCouponContent = (coupon: CouponCode) => {
    const usagePercentage = (coupon.usedCount / coupon.usageLimit) * 100;
    
    return (
      <div className="space-y-3">
        <div className="grid grid-cols-2 lg:grid-cols-4 gap-4 text-sm">
          <div>
            <span className="text-gray-600">Code:</span>
            <div className="flex items-center gap-2">
              <span className="font-mono font-medium">{coupon.code}</span>
              <button
                onClick={() => handleCopy(coupon.code)}
                className="p-1 hover:bg-gray-100 rounded transition-colors"
                title="Copy code"
              >
                {copiedCode === coupon.code ? (
                  <Check className="h-3 w-3 text-green-600" />
                ) : (
                  <Copy className="h-3 w-3 text-gray-400" />
                )}
              </button>
            </div>
          </div>
          <div>
            <span className="text-gray-600">Discount:</span>
            <p className="font-medium">
              {coupon.discountType === 'percentage' ? `${coupon.discountValue}%` : `₹${coupon.discountValue}`}
            </p>
          </div>
          <div>
            <span className="text-gray-600">Min Order:</span>
            <p className="font-medium">₹{coupon.minOrderValue}</p>
          </div>
          <div>
            <span className="text-gray-600">Usage:</span>
            <p className="font-medium">{coupon.usedCount}/{coupon.usageLimit}</p>
          </div>
        </div>
        
        <div className="w-full bg-gray-200 rounded-full h-2">
          <div 
            className="bg-blue-600 h-2 rounded-full transition-all duration-300" 
            style={{ width: `${Math.min(usagePercentage, 100)}%` }}
          />
        </div>
        
        <div className="flex items-center gap-4 text-sm text-gray-500">
          <span>Valid: {new Date(coupon.validFrom).toLocaleDateString()} - {new Date(coupon.validTo).toLocaleDateString()}</span>
          <span>•</span>
          <span>Target: {coupon.targetAudience}</span>
        </div>
      </div>
    );
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold">Coupon Management</h1>
          <p className="text-gray-600">Create and manage discount coupons</p>
        </div>
        <Button onClick={() => handleOpenForm(undefined, false)}>
          <Plus className="mr-2 h-4 w-4" />
          Create Coupon
        </Button>
      </div>

      <CouponStats coupons={coupons} />

      {copiedCode && (
        <div className="fixed top-4 right-4 bg-green-500 text-white px-4 py-2 rounded-lg shadow-lg z-50 flex items-center gap-2">
          <Check className="h-4 w-4" />
          Copied "{copiedCode}" to clipboard
        </div>
      )}

      {/* Coupons List with Bulk Actions */}
      <MarketingList
        items={coupons}
        onView={(coupon) => handleOpenForm(coupon as CouponCode, true)}
        onEdit={(coupon) => handleOpenForm(coupon as CouponCode, false)}
        onDelete={(item) => handleDelete(item as CouponCode)}
        onBulkAction={handleBulkAction}
        title="Coupon Management"
        itemType="coupon"
        renderItemContent={(item) => renderCouponContent(item as CouponCode)}
        statusFilter={['all', 'active', 'inactive', 'expired']}
      />

      <Modal isOpen={isFormOpen} onClose={handleCloseForm} title={isReadOnly ? 'View Coupon' : (selectedCoupon ? 'Edit Coupon' : 'Create Coupon')}>
        <CouponForm 
          initialData={selectedCoupon}
          isReadOnly={isReadOnly}
          onSubmit={handleSave}
          onCancel={handleCloseForm}
        />
      </Modal>
    </div>
  );
}
