import type { Order, Product, TeamMember, DashboardStats, Coupon, Report, Hub } from "./types"

export const mockDashboardStats: DashboardStats = {
  totalOrders: 12458,
  totalSales: 2456780,
  totalUsers: 8945,
  totalProducts: 120,
  pendingOrders: 145,
  lowStockItems: 23,
  activeDeliveries: 67,
  todayOrders: 234,
}

export const mockOrders: Order[] = [
  {
    id: "1",
    orderNumber: "ORD-2024-001",
    customer: {
      name: "Rajesh Kumar",
      phone: "+91 98765 43210",
      email: "rajesh@email.com",
      address: "123, Gandhi Street, Chennai - 600001",
    },
    items: [
      { id: "1", productId: "p1", name: "Pomfret Fish", quantity: 2, price: 450, unit: "kg" },
      { id: "2", productId: "p2", name: "Tiger Prawns", quantity: 1, price: 650, unit: "kg" },
    ],
    status: "processing",
    source: "app",
    paymentMethod: "online",
    paymentStatus: "paid",
    total: 1550,
    deliverySlot: "10:00 AM - 12:00 PM",
    assignedTo: "DEL-001",
    hub: "Chennai Central",
    zone: "Zone A",
    createdAt: "2024-01-15T08:30:00Z",
    updatedAt: "2024-01-15T09:00:00Z",
  },
  {
    id: "2",
    orderNumber: "ORD-2024-002",
    customer: {
      name: "Priya Sharma",
      phone: "+91 87654 32109",
      email: "priya@email.com",
      address: "456, Nehru Road, Chennai - 600002",
    },
    items: [{ id: "3", productId: "p3", name: "Seer Fish", quantity: 1, price: 580, unit: "kg" }],
    status: "received",
    source: "whatsapp",
    paymentMethod: "cod",
    paymentStatus: "pending",
    total: 580,
    deliverySlot: "2:00 PM - 4:00 PM",
    hub: "Chennai Central",
    zone: "Zone B",
    createdAt: "2024-01-15T09:15:00Z",
    updatedAt: "2024-01-15T09:15:00Z",
  },
  {
    id: "3",
    orderNumber: "ORD-2024-003",
    customer: {
      name: "Anand Pillai",
      phone: "+91 76543 21098",
      email: "anand@email.com",
      address: "789, MG Road, Chennai - 600003",
    },
    items: [
      { id: "4", productId: "p4", name: "Fresh Salmon", quantity: 1, price: 800, unit: "kg" },
      { id: "5", productId: "p5", name: "Crab Meat", quantity: 2, price: 700, unit: "kg" },
    ],
    status: "packed",
    source: "web",
    paymentMethod: "online",
    paymentStatus: "paid",
    total: 2200,
    deliverySlot: "4:00 PM - 6:00 PM",
    assignedTo: "DEL-002",
    hub: "Chennai South",
    zone: "Zone C",
    createdAt: "2024-01-15T10:00:00Z",
    updatedAt: "2024-01-15T11:30:00Z",
  },
  {
    id: "4",
    orderNumber: "ORD-2024-004",
    customer: {
      name: "Meena Devi",
      phone: "+91 65432 10987",
      email: "meena@email.com",
      address: "321, Anna Salai, Chennai - 600004",
    },
    items: [{ id: "6", productId: "p6", name: "Squid Rings", quantity: 2, price: 420, unit: "kg" }],
    status: "out_for_delivery",
    source: "instagram",
    paymentMethod: "wallet",
    paymentStatus: "paid",
    total: 840,
    deliverySlot: "6:00 AM - 8:00 AM",
    assignedTo: "DEL-003",
    hub: "Chennai Central",
    zone: "Zone A",
    createdAt: "2024-01-15T05:30:00Z",
    updatedAt: "2024-01-15T06:45:00Z",
  },
  {
    id: "5",
    orderNumber: "ORD-2024-005",
    customer: {
      name: "Karthik Rajan",
      phone: "+91 54321 09876",
      email: "karthik@email.com",
      address: "654, Mount Road, Chennai - 600005",
    },
    items: [
      { id: "7", productId: "p7", name: "Tuna Fish", quantity: 1, price: 520, unit: "kg" },
    ],
    status: "delivered",
    source: "facebook",
    paymentMethod: "online",
    paymentStatus: "paid",
    total: 520,
    deliverySlot: "10:00 AM - 12:00 PM",
    assignedTo: "DEL-001",
    hub: "Chennai North",
    zone: "Zone D",
    createdAt: "2024-01-14T14:00:00Z",
    updatedAt: "2024-01-14T17:30:00Z",
  },
]

export const mockProducts: Product[] = [
  {
    id: "p1",
    name: "Pomfret Fish",
    sku: "SF-POM-001",
    category: "Fish",
    price: 450,
    unit: "kg",
    stock: 85,
    lowStockThreshold: 20,
    status: "active",
    description: "Fresh white pomfret fish",
  },
  {
    id: "p2",
    name: "Tiger Prawns",
    sku: "SF-PRA-001",
    category: "Prawns",
    price: 650,
    unit: "kg",
    stock: 60,
    lowStockThreshold: 15,
    status: "active",
    description: "Fresh tiger prawns",
  },
  {
    id: "p3",
    name: "Seer Fish",
    sku: "SF-SEE-001",
    category: "Fish",
    price: 580,
    unit: "kg",
    stock: 45,
    lowStockThreshold: 20,
    status: "active",
    description: "Fresh seer fish steaks",
  },
  {
    id: "p4",
    name: "Fresh Salmon",
    sku: "SF-SAL-001",
    category: "Fish",
    price: 800,
    unit: "kg",
    stock: 30,
    lowStockThreshold: 10,
    status: "active",
    description: "Fresh salmon fillets",
  },
  {
    id: "p5",
    name: "Crab Meat",
    sku: "SF-CRA-001",
    category: "Crab",
    price: 700,
    unit: "kg",
    stock: 40,
    lowStockThreshold: 15,
    status: "active",
    description: "Fresh crab meat",
  },
  {
    id: "p6",
    name: "Squid Rings",
    sku: "SF-SQU-001",
    category: "Squid",
    price: 420,
    unit: "kg",
    stock: 55,
    lowStockThreshold: 20,
    status: "active",
    description: "Cleaned squid rings",
  },
  {
    id: "p7",
    name: "Tuna Fish",
    sku: "SF-TUN-001",
    category: "Fish",
    price: 520,
    unit: "kg",
    stock: 38,
    lowStockThreshold: 15,
    status: "active",
    description: "Fresh tuna steaks",
  },
  {
    id: "p8",
    name: "Mackerel Fish",
    sku: "SF-MAC-001",
    category: "Fish",
    price: 280,
    unit: "kg",
    stock: 70,
    lowStockThreshold: 25,
    status: "active",
    description: "Fresh mackerel fish",
  },
  {
    id: "p9",
    name: "Lobster",
    sku: "SF-LOB-001",
    category: "Lobster",
    price: 1200,
    unit: "kg",
    stock: 15,
    lowStockThreshold: 5,
    status: "active",
    description: "Fresh lobster",
  },
  {
    id: "p10",
    name: "Anchovy",
    sku: "SF-ANC-001",
    category: "Fish",
    price: 320,
    unit: "kg",
    stock: 50,
    lowStockThreshold: 20,
    status: "active",
    description: "Fresh anchovy fish",
  },
  {
    id: "p11",
    name: "Chicken Breast",
    sku: "MT-CHK-001",
    category: "Chicken",
    price: 280,
    unit: "kg",
    stock: 60,
    lowStockThreshold: 20,
    status: "active",
    description: "Fresh boneless chicken breast",
  },
  {
    id: "p12",
    name: "Mutton Curry Cut",
    sku: "MT-MUT-001",
    category: "Mutton",
    price: 700,
    unit: "kg",
    stock: 40,
    lowStockThreshold: 15,
    status: "active",
    description: "Fresh mutton curry cut",
  },
  {
    id: "p13",
    name: "Free Range Eggs",
    sku: "EG-FRE-001",
    category: "Egg",
    price: 120,
    unit: "dozen",
    stock: 100,
    lowStockThreshold: 30,
    status: "active",
    description: "Pack of 12 free range eggs",
  },
  {
    id: "p14",
    name: "Turmeric Powder",
    sku: "SP-TUR-001",
    category: "Spices",
    price: 180,
    unit: "kg",
    stock: 150,
    lowStockThreshold: 50,
    status: "active",
    description: "Pure turmeric powder",
  },
  {
    id: "p15",
    name: "Red Chilli Powder",
    sku: "SP-CHI-001",
    category: "Spices",
    price: 200,
    unit: "kg",
    stock: 120,
    lowStockThreshold: 40,
    status: "active",
    description: "Spicy red chilli powder",
  },
]

export const mockTeamMembers: TeamMember[] = [
  {
    id: "TM-001",
    name: "Suresh Kumar",
    email: "suresh@admin.com",
    phone: "+91 98765 43210",
    role: "delivery",
    department: "delivery",
    status: "active",
    assignedOrders: 12,
    completedOrders: 1456,
    rating: 4.8,
    hub: "Chennai Central",
  },
  {
    id: "TM-002",
    name: "Lakshmi Priya",
    email: "lakshmi@admin.com",
    phone: "+91 87654 32109",
    role: "packing",
    department: "packing",
    status: "active",
    assignedOrders: 8,
    completedOrders: 2340,
    hub: "Chennai Central",
  },
  {
    id: "TM-003",
    name: "Murugan S",
    email: "murugan@admin.com",
    phone: "+91 76543 21098",
    role: "procurement",
    department: "procurement",
    status: "active",
    assignedOrders: 0,
    completedOrders: 890,
    hub: "Chennai South",
  },
  {
    id: "TM-004",
    name: "Kavitha R",
    email: "kavitha@admin.com",
    phone: "+91 65432 10987",
    role: "delivery",
    department: "delivery",
    status: "active",
    assignedOrders: 15,
    completedOrders: 1890,
    rating: 4.9,
    hub: "Chennai North",
  },
]

export const mockCoupons: Coupon[] = [
  {
    id: "CPN-001",
    code: "WELCOME20",
    type: "percentage",
    value: 20,
    minOrderValue: 500,
    maxDiscount: 200,
    validFrom: "2024-01-01",
    validTo: "2024-03-31",
    usageLimit: 1000,
    usedCount: 456,
    status: "active",
  },
  {
    id: "CPN-002",
    code: "FLAT100",
    type: "fixed",
    value: 100,
    minOrderValue: 800,
    validFrom: "2024-01-15",
    validTo: "2024-02-15",
    usageLimit: 500,
    usedCount: 234,
    status: "active",
  },
]

export const mockReports: Report[] = [
  {
    id: "RPT-001",
    name: "Daily Sales Report",
    type: "sales",
    period: "daily",
    generatedAt: "2024-01-15T00:00:00Z",
    status: "ready",
  },
  {
    id: "RPT-002",
    name: "Weekly Stock Report",
    type: "stock",
    period: "weekly",
    generatedAt: "2024-01-14T00:00:00Z",
    status: "ready",
  },
  {
    id: "RPT-003",
    name: "Packing Report",
    type: "packing",
    period: "daily",
    generatedAt: "2024-01-15T00:00:00Z",
    status: "generating",
  },
]

export const mockHubs: Hub[] = [
  {
    id: "HUB-001",
    name: "Chennai Central",
    address: "100, Central Hub Road, Chennai - 600001",
    zones: ["Zone A", "Zone B"],
    status: "active",
  },
  {
    id: "HUB-002",
    name: "Chennai South",
    address: "200, South Hub Road, Chennai - 600020",
    zones: ["Zone C", "Zone D"],
    status: "active",
  },
  {
    id: "HUB-003",
    name: "Chennai North",
    address: "300, North Hub Road, Chennai - 600050",
    zones: ["Zone E", "Zone F"],
    status: "active",
  },
]

export const salesTrendData = [
  { date: "Jan 1", sales: 45000, orders: 120 },
  { date: "Jan 2", sales: 52000, orders: 145 },
  { date: "Jan 3", sales: 48000, orders: 132 },
  { date: "Jan 4", sales: 61000, orders: 168 },
  { date: "Jan 5", sales: 55000, orders: 152 },
  { date: "Jan 6", sales: 67000, orders: 185 },
  { date: "Jan 7", sales: 72000, orders: 198 },
  { date: "Jan 8", sales: 58000, orders: 160 },
  { date: "Jan 9", sales: 63000, orders: 175 },
  { date: "Jan 10", sales: 69000, orders: 190 },
  { date: "Jan 11", sales: 75000, orders: 205 },
  { date: "Jan 12", sales: 71000, orders: 195 },
  { date: "Jan 13", sales: 78000, orders: 215 },
  { date: "Jan 14", sales: 82000, orders: 225 },
]

export const orderStatusData = [
  { name: "Received", value: 145, color: "#3b82f6" },
  { name: "Processing", value: 89, color: "#f59e0b" },
  { name: "Packed", value: 67, color: "#8b5cf6" },
  { name: "Out for Delivery", value: 45, color: "#06b6d4" },
  { name: "Delivered", value: 234, color: "#10b981" },
]

export const categoryStockData = [
  { category: "Fish", stock: 30, lowStock: 10 },
  { category: "Chicken", stock: 45, lowStock: 20 },
  { category: "Mutton", stock: 40, lowStock: 15 },
  { category: "Egg", stock: 100, lowStock: 30 },
  { category: "Spices", stock: 450, lowStock: 150 },
]
